name: jest-ci

on:
    push:
        branches-ignore:
            - 'master'

jobs:
    test-front:
        runs-on: macos-12
        steps:
            - name: Check out code
              uses: actions/checkout@v2
            - name: Goto client and run tests
              run: cd client && npm i && npm test
